/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/peter/Data/Anlogic_projects/FA201_Lichee_nano/awg_v1/al_ip/output_ddr.v
 ** Date	:	2022 04 01
 ** TD version	:	5.0.28716
\************************************************************/

`timescale 1ns / 1ps

module output_ddr ( q, clk, d1, d2, rst );
output 		q;
input  		clk;
input  		d1;
input  		d2;
input  		rst;

		AL_LOGIC_ODDR #(
		.SRMODE("SYNC"))
		oddr (
		.q(q),
		.clk(clk),
		.d1(d1),
		.d2(d2),
		.rst(rst));

endmodule