/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/peter/Data/Anlogic_projects/FA201_Lichee_nano/awg_v1/al_ip/pll_clock.v
 ** Date	:	2022 04 02
 ** TD version	:	5.0.28716
\************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:             50.000Mhz
//	Clock multiplication factor: 5
//	Clock division factor:       2
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C0        	| 125.000000MHZ	| 0  DEG     
//		C1        	| 125.000000MHZ	| 90 DEG     
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

module pll_clock(refclk,
		reset,
		clk0_out,
		clk1_out);

	input refclk;
	input reset;
	output clk0_out;
	output clk1_out;

	wire clk0_buf;

	AL_LOGIC_BUFG bufg_fbk( .i(clk0_buf), .o(clk0_out) );

	AL_PHY_PLL #(.DPHASE_SOURCE("DISABLE"),
		.FIN("50.000"),
		.FEEDBK_MODE("ZERODELAY"),
		.FEEDBK_PATH("CLKC0_EXT"),
		.STDBY_ENABLE("DISABLE"),
		.PLLRST_ENA("ENABLE"),
		.SYNC_ENABLE("DISABLE"),
		.DERIVE_PLL_CLOCKS("DISABLE"),
		.GEN_BASIC_CLOCK("DISABLE"),
		.GMC_GAIN("2"),
		.ICP_CURRENT(9),
		.KVCO("2"),
		.LPF_CAPACITOR("1"),
		.LPF_RESISTOR(8),
		.REFCLK_DIV(2),
		.FBCLK_DIV(5),
		.CLKC0_ENABLE("ENABLE"),
		.CLKC0_DIV(8),
		.CLKC0_CPHASE(7),
		.CLKC0_FPHASE("0"),
		.CLKC1_ENABLE("ENABLE"),
		.CLKC1_DIV(8),
		.CLKC1_CPHASE(1),
		.CLKC1_FPHASE("0")	)
	pll_inst (.refclk(refclk),
		.pllreset(reset),
		.stdby(1'b0),
		.ext_lock(open),
		.load_reg(1'b0),
		.scanclk(1'b0),
		.phaseupdown(1'b0),
		.phasestep(1'b0),
		.phcntsel(3'b000),
		.phasedone(open),
		.fbclk(clk0_out),
		.clkc({open, open, open, clk1_out, clk0_buf}));

endmodule
