/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/peter/Data/Anlogic_projects/FA201_Lichee_nano/awg_v1/al_ip/sin_table.v
 ** Date	:	2022 04 06
 ** TD version	:	5.0.28716
\************************************************************/

`timescale 1ns / 1ps

module sin_rom ( 
	doa, addra, clka, rsta, 
	dob, addrb, clkb, rstb );

	output [12:0] doa;
	output [12:0] dob;

	input  [11:0] addra;
	input  [11:0] addrb;
	input  clka;
	input  clkb;
	input  rsta;
	input  rstb;




	AL_LOGIC_BRAM #( .DATA_WIDTH_A(13),
				.DATA_WIDTH_B(13),
				.ADDR_WIDTH_A(12),
				.ADDR_WIDTH_B(12),
				.DATA_DEPTH_A(4096),
				.DATA_DEPTH_B(4096),
				.MODE("DP"),
				.REGMODE_A("NOREG"),
				.REGMODE_B("NOREG"),
				.IMPLEMENT("9K"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("../source/sin_rom.mif"),
				.FILL_ALL("NONE"))
			inst(
				.dia({13{1'b0}}),
				.dib({13{1'b0}}),
				.addra(addra),
				.addrb(addrb),
				.cea(1'b1),
				.ceb(1'b1),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(clkb),
				.wea(1'b0),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(rsta),
				.rstb(rstb),
				.doa(doa),
				.dob(dob));


endmodule